HeatTemplateFormatVersion: '2012-12-12'
Description: 'HEAT Template - private chef server'
Parameters:
  KeyName: 
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances
    Type: String
    Default: default
  InstanceType:
    Description: Use this flavor
    Type: String
    Default: bm.small
  ChefClientImage:
    Description: Chef Client Image
    Type: String
Resources:
  PrivateChefServerLaunch:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId:
        {Ref: ChefClientImage}
      InstanceType: {Ref: InstanceType}
      KeyName: {Ref: KeyName}
    Metadata:
      TripleO::ImageBuilder::Elements: [ "private-chef-client" ]
  PrivateChefServer:
    Type: OS::Heat::InstanceGroup
    Properties:
      LaunchConfigurationName: PrivateChefServerLaunch
      AvailabilityZones: [ 1 ]
      Size: '1'
